# Generated by Django 5.2.1 on 2025-07-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryabc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paketlaundry',
            name='kode_paket',
        ),
        migrations.AddField(
            model_name='customer',
            name='paket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='laundryabc_app.paketlaundry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paketlaundry',
            name='deskripsi',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='paketlaundry',
            name='nama_paket',
            field=models.CharField(max_length=5),
        ),
    ]
